export const siteData = {
  brand: {
    name: "RK Interiors",
    tagline: "SPACES FOR BETTER LIVING",
    phone: "+91 81787 41250",
    secondaryPhone: "+91 92881 36676",
    whatsapp: "918178741250",
    email: "contact@rkinteriorspatna.com",
    address: "Patna, Bihar",
    experienceCentreAddress: "Patna, Bihar",
    workingHours: "Mon – Sat, 10 AM – 8 PM",
  },
  metrics: [
    { value: "10+", label: "Years of Experience", description: "Designing spaces, building trust.", icon: "users" as const },
    { value: "20L+", label: "Catalogue Products", description: "A wider world of possibilities.", icon: "package" as const },
    { value: "3,500+", label: "Spaces Designed", description: "Homes and businesses across Patna.", icon: "ruler" as const },
    { value: "45-Day", label: "Move-In Guarantee", description: "On-time. As promised.", icon: "shield" as const },
  ],
  services: [
    {
      title: "Full Home Interiors",
      description: "Complete homes designed around your lifestyle.",
      image: "/images/after.png",
    },
    {
      title: "Modular Kitchens",
      description: "Functional, stylish kitchens for everyday living.",
      image: "/images/featured-secondary-1.jpg",
    },
    {
      title: "Luxury Interiors",
      description: "Tailored interiors that redefine elegance.",
      image: "/images/service-luxury.jpg",
    },
    {
      title: "Renovations",
      description: "Expert solutions to upgrade your home.",
      image: "/images/experience-3.jpg",
    },
    {
      title: "Office Interiors",
      description: "Workspaces that inspire productivity.",
      image: "/images/featured-4.jpg",
    },
  ],
  featuredProject: {
    label: "FEATURED PROJECT",
    title: "A Modern 3BHK",
    location: "in Kankarbagh, Patna",
    tags: ["Residential", "3BHK", "Contemporary"],
    description:
      "A warm, contemporary home designed around comfort, storage, natural textures and thoughtful lighting. Clean lines blend with warm textures and thoughtful lighting to create a space that feels both modern and timeless.",
    image: "/images/featured-main.jpg",
    secondaryImages: [
      "/images/featured-secondary-1.jpg",
      "/images/featured-secondary-2.jpg",
    ],
  },
  processSteps: [
    { number: "01", title: "Understand", description: "Your needs, lifestyle and budget.", image: "/images/process-understand.jpg" },
    { number: "02", title: "Site Visit", description: "We measure and understand your space.", image: "/images/process-sitevisit.jpg" },
    { number: "03", title: "3D Design", description: "See your space before execution.", image: "/images/process-3ddesign.jpg" },
    { number: "04", title: "Material Selection", description: "Choose finishes and materials.", image: "/images/process-materials.jpg" },
    { number: "05", title: "Execution", description: "Our team handles the build.", image: "/images/process-execution.jpg" },
    { number: "06", title: "Handover", description: "Final checks and completion.", image: "/images/process-handover.jpg" },
  ],
  benefits: [
    { title: "Personalized Design", description: "Spaces tailored to your lifestyle." },
    { title: "Premium Materials", description: "Quality you can see, touch and live with." },
    { title: "Transparent Pricing", description: "No surprises, just clarity." },
    { title: "Experienced Team", description: "Skilled, reliable and local." },
    { title: "End-to-End Execution", description: "From design to handover, seamlessly." },
    { title: "Dedicated Support", description: "We're here for you, even after handover." },
  ],
  projects: [
    { id: "1", title: "Modern Home", location: "Patna", category: "Full Homes", image: "/images/portfolio-1.jpg" },
    { id: "2", title: "Living Room", location: "Patna", category: "Full Homes", image: "/images/portfolio-2.jpg" },
    { id: "3", title: "Modular Kitchen", location: "Nawada", category: "Kitchens", image: "/images/portfolio-3.jpg" },
    { id: "4", title: "Luxury Interior", location: "Gaya", category: "Full Homes", image: "/images/portfolio-4.jpg" },
    { id: "5", title: "Office Space", location: "Patna", category: "Commercial", image: "/images/portfolio-5.jpg" },
    { id: "6", title: "Master Bedroom", location: "Patna", category: "Bedrooms", image: "/images/portfolio-6.jpg" },
    { id: "7", title: "Contemporary Flat", location: "Bhagalpur", category: "Full Homes", image: "/images/portfolio-7.jpg" },
    { id: "8", title: "Home Renovation", location: "Gaya", category: "Renovations", image: "/images/portfolio-8.jpg" },
    { id: "9", title: "Cozy Bedroom", location: "Patna", category: "Bedrooms", image: "/images/portfolio-9.jpg" },
    { id: "10", title: "Designer Kitchen", location: "Nalanda", category: "Kitchens", image: "/images/portfolio-10.jpg" },
    { id: "11", title: "Minimalist Home", location: "Patna", category: "Full Homes", image: "/images/portfolio-11.jpg" },
    { id: "12", title: "Elegant Living", location: "Vaishali", category: "Full Homes", image: "/images/portfolio-12.jpg" },
    { id: "13", title: "Luxury Bedroom", location: "Patna", category: "Bedrooms", image: "/images/portfolio-13.jpg" },
    { id: "14", title: "Open Kitchen", location: "Patna", category: "Kitchens", image: "/images/portfolio-14.jpg" },
    { id: "15", title: "Studio Apartment", location: "Gaya", category: "Full Homes", image: "/images/portfolio-15.jpg" },
    { id: "16", title: "Modern Kitchen", location: "Patna", category: "Kitchens", image: "/images/portfolio-16.jpg" },
    { id: "17", title: "Guest Bedroom", location: "Nalanda", category: "Bedrooms", image: "/images/portfolio-17.jpg" },
    { id: "18", title: "Showroom Office", location: "Bhagalpur", category: "Commercial", image: "/images/portfolio-18.jpg" },
  ],
  portfolioFilters: ["All", "Full Homes", "Kitchens", "Bedrooms", "Commercial", "Renovations"],
  testimonials: [
    {
      rating: 5,
      text: "RK Interiors transformed our house into a home. The team was professional, patient and incredibly detail-oriented.",
      name: "Priya & Abhishek",
      location: "Patna",
      projectType: "3BHK, Full Home",
      image: "/images/portfolio-1.jpg",
    },
    {
      rating: 5,
      text: "Great design sense and smooth execution. They understood exactly what we wanted and delivered beyond expectations.",
      name: "Rahul Sinha",
      location: "Patna",
      projectType: "Modular Kitchen",
      image: "/images/portfolio-3.jpg",
    },
    {
      rating: 5,
      text: "The experience centre really helped us visualize our home. Highly recommended for anyone in Patna.",
      name: "Neha & Kunal",
      location: "Patna",
      projectType: "2BHK Interiors",
      image: "/images/portfolio-2.jpg",
    },
  ],
  contact: {
    designingOptions: [
      "Full Home",
      "Kitchen",
      "Bedroom",
      "Living Room",
      "Office",
      "Renovation",
      "Other",
    ],
    budgetOptions: [
      "₹3–5L",
      "₹5–10L",
      "₹10–20L",
      "₹20L+",
      "Not sure yet",
    ],
  },
  quickLinks: ["Home", "About", "Services", "Projects", "Locations", "Blogs", "Contact"],
  footerServices: [
    "Full Home Interiors",
    "Modular Kitchens",
    "Bedrooms",
    "Office Interiors",
    "Renovations",
    "Interior Consultation",
  ],
  locations: [
    "Patna", "Gaya", "Nalanda", "Nawada", "Vaishali", "Jamui",
    "Begusarai", "Buxar", "Bhagalpur", "Darbhanga", "Gopalganj",
    "Kaimur", "Khagaria", "Purnia", "Rohtas", "Saharsa",
    "Samastipur", "Saran", "Siwan", "Sheikhpura", "Supaul",
  ],
};
